modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="funitems"
version="1.0.0"
displayName="FunItems"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Raemex, MCreator"

[[dependencies.funitems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




